# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build status

on:
  push:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install coveralls
    - name: Test
      run: |
        # sed --version
        python tests/test-suite.py @timing-tests.suites -x test-python-sed-3.7.exclude
        python tests/test-suite.py @timing-tests.suites -x test-python-sed-3.7.exclude -b sed

    - name: Coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github