# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build status

on:
  push:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install coveralls
    - name: Test
      run: |
        # coverage run --include PythonSed/sed.py tests/test_script_io.py
        # coverage run --include PythonSed  -a tests/test-suite.py @all-tests.suites -x test-python-sed-3.7.exclude
        # ls /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/PythonSed/sed.py
        coverage run tests/test_script_io.py
        coverage report

    - name: Coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls --service=github